# image will be published to ghcr.io/<user>/<name>
name: fedora-bluekit
# description will be included in the image's metadata
description: My personal Fedora universal-blue image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      # copy static configurations
      #
      # copies config/files/usr into your image's /usr
      #
      # configuration you wish to end up in /etc/ on the booted system
      # should be added into /usr/etc/ as that is the proper "distro"
      # config directory on ostree. Read more in the files module's README
      - usr: /usr
      - rpm-gpg: /etc/pki/rpm-gpg
      - rpm-gpg: /usr/etc/pki/rpm-gpg
      - yum.repos.d: /etc/yum.repos.d
      - yum.repos.d: /usr/etc/yum.repos.d

  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      # Some GUI apps on host for better integration
      - gnome-clocks
      - nextcloud-client
      - nextcloud-client-nautilus
      - pgadmin4

      # Tilix as default terminal
      - tilix
      - tilix-nautilus

      # Official docker-engine release
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

      # HP printer and scanner drivers
      - hplip
      - sane-backends-drivers-scanners
      - simple-scan
    remove:
      # removing default gnome-terminal in favour of tilix
      - gnome-terminal
      - gnome-terminal-nautilus

      # default firefox removed in favor of flatpak
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.google.Chrome
        - com.mattjakeman.ExtensionManager
        - com.slack.Slack
        - com.visualstudio.code
        - org.gnome.Evince
        - org.gnome.Loupe
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.libreoffice.LibreOffice
        - org.mozilla.firefox
        - rest.insomnia.Insomnia
      remove:
        - org.gnome.Extensions
        - org.gnome.Totem

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
